### PR TITLE
Update Bazel and all dependencies to latest

### PR DESCRIPTION
**Pull request by philwo**
We were lagging behind quite a bit, but this brings everything back to latest versions.

I manually verified that the change does not negatively affect the size of the generated binaries or the structure of the NPM package.

### CODE REVIEW

**Review by fweikert — APPROVED** [review]

**Comment by fweikert** [comment]
Nice, thank you!

I triggered a rerun of the failing Windows test.

**Comment by philwo** [comment]
Huh... that failure on Windows is strange:

> compilepkg: could not create directory for _empty.go: mkdir C:\b\2hhx3mgx\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\platforms\github_com_bazelbuild_bazelisk_platforms: Cannot create a file when that file already exists.

I don't immediately have an idea what might cause it, but I can try a few things in this PR later or in the next days to fix this.

**Comment by meteorcloudy** [comment]
The error seemed to be through at https://github.com/bazelbuild/rules_go/blob/ed56d7e5b6a7bf833169372742c1ff72f501846a/go/tools/builders/compilepkg.go#L206-L208, if I try to build `//platforms:platforms_test` alone, it doesn't throw the error. I think there is some conflict between actions.

**Comment by fweikert** [comment]
Closing in favor of https://github.com/bazelbuild/bazelisk/pull/403

**Pull request closed without merging**
