### PR TITLE
Update: Go `1.23.0` and Bazel `7.3.1`

### PR DESCRIPTION
**Pull request by albertocavalcante**
Bump Go and Bazel versions.

- https://go.dev/doc/go1.23
- https://github.com/bazelbuild/bazel/releases/tag/7.3.1

### CODE REVIEW

**Comment by albertocavalcante** [comment]
@fweikert @meteorcloudy are you able to restart the CI? Thanks!

**Comment by meteorcloudy** [comment]
I retried the failing job, it looks like a legit failure on windows, can you take a look?

**Comment by albertocavalcante** [comment]
Thanks @meteorcloudy! Sure, I'll take a look.

**Comment by albertocavalcante** [comment]
Windows failures due to:

- https://github.com/bazelbuild/rules_go/issues/4049
- https://github.com/bazelbuild/rules_go/pull/4050

**Comment by albertocavalcante** [comment]
@meteorcloudy Windows CI passed. Can you please review it?

**Review by fweikert — APPROVED** [review]

**Pull request merged**
