### PR TITLE
chore(bazel): add MODULE.bazel files for bzlmod

### PR DESCRIPTION
**Pull request by mmorel-35**
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@mmorel-35 Can you please upgrade Bazel version in .bazelversion to 7.0.2? It'll actually switch the default build to Bzlmod.

**Comment by meteorcloudy** [comment]
It's also fine if you think this should be done in a follow-up PR. Thanks for the contribution!

**Comment by mmorel-35** [comment]
I could but I agree that it deserves to be two separated PR

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Comment by jwnimmer-tri** [comment]
> It's also fine if you think this should be done in a follow-up PR.

I've submitted https://github.com/bazelbuild/bazelisk/pull/564 for this.

**Pull request merged**
