### PR TITLE
Support BAZELISK_NOJDK in Bazelisk Go. Fix #267 and #430

### LINKED ISSUE #267: bazel nojdk version
We don't use java at all and would like to use the nojdk version of bazel. (less to download in our ci/cd jobs).

Is it possible to add support for it? Does it actually support it now and I just have not figured it out?

### PR DESCRIPTION
**Pull request by ql-owo-lp**
Support BAZELISK_NOJDK in Bazelisk Go. Fix #267 and #430

### CODE REVIEW

**Review by fweikert — APPROVED** [review]

**Comment by fweikert** [comment]
Unfortunately the config work is conflicting with https://github.com/bazelbuild/bazelisk/pull/462 :( Sorry for the additional work

**Comment by ql-owo-lp** [comment]
> Unfortunately the config chnage is conflicting with #462 :( Sorry for the additional work

Let me know if any more changes are needed

**Comment by auzhva** [comment]
Hi,

Is anything else needed for this PR?

Appreciate if could be merged...

**Comment by JayBazuzi** [comment]
@ql-owo-lp would you be willing to fix the conflicts on this change?

**Comment by JayBazuzi** [comment]
This PR can be closed now that #531 is done.

**Comment by fweikert** [comment]
I'll close this in favor of #531. @ql-owo-lp , thank you for the initial work, and sorry for the review delays.

**Review by Sec32fun32 — APPROVED** [review]

**Pull request closed without merging**
