### PR TITLE
Add support for `tools/bazel.ps1` and `tools/bazel.bat` on Windows

### PR DESCRIPTION
**Pull request by UebelAndre**
closes https://github.com/bazelbuild/bazelisk/issues/416

### CODE REVIEW

**Comment by UebelAndre** [comment]
@philwo @fweikert hey, would either of you be able to take a look at this PR? 😅

**Comment by fweikert** [comment]
Nice, thanks for this PR (and especially for adding a test!). I'll reserve some time tomorrow to work this PR and the others in our backlog.

**Review by fweikert — CHANGES_REQUESTED** [review]

**Review by fweikert — APPROVED** [review]
Thank you so much, especially for adding the test!

**Comment by UebelAndre** [comment]
> Thank you so much, especially for adding the test!

Thanks for the review! Would it be possible to get a new release with this change in it? 🙏

**Comment by fweikert** [comment]
Yeah, I'll try to merge some more PRs, then I'll cut a new release tomorrow (Thursday).

**Comment by UebelAndre** [comment]
> Yeah, I'll try to merge some more PRs, then I'll cut a new release tomorrow (Thursday).

Thanks! I was gonna make an issue to track the release but seems https://github.com/bazelbuild/bazelisk/issues/411 already exists. I'll subscribe to that and I'm eagerly looking forward to the new version 😄

**Pull request merged**
