### PR TITLE
add arm64 support and build target

### PR DESCRIPTION
**Pull request by lizan**

### CODE REVIEW

**Comment by lizan** [comment]
ping? @philwo

**Comment by philwo** [comment]
Thank you! And sorry for the delay.

**Comment by philwo** [comment]
I will create a new Bazelisk release on Monday that incorporates this.

**Comment by lizan** [comment]
@philwo did you have a chance to make a release? we're waiting to switch to official bazelisk

**Comment by philwo** [comment]
@lizan Bazelisk v1.6.0 with this feature included is out: https://github.com/bazelbuild/bazelisk/releases/tag/v1.6.0 - sorry for the delay!

**Pull request merged**
