### PR TITLE
Fetch all incompatible flag issues, including the closed ones.

### PR DESCRIPTION
**Pull request by dslomov**

### CODE REVIEW

**Comment by dslomov** [comment]
hold on, maybe I am wrong.

**Comment by dslomov** [comment]
This request: https://api.github.com/search/issues?per_page=100&q=repo:bazelbuild/bazel+label:migration-0.28

does return closed issues (search for disallow_legacy_javainfo). Why is the flag not picked up?

**Comment by dslomov** [comment]
ahhh gotcha. Thank you!

**Comment by philwo** [comment]
@dslomov @laurentlb I prepared a PR, please quickly check and LGTM if it looks good: https://github.com/bazelbuild/continuous-integration/pull/802

**Pull request closed without merging**
